### PR TITLE
Fix ubuntu 16.04 tests

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I don't know whats wrong with travis but it works on my machine. Probably some security thing in their LXC's.

**Comment by nickjj** [comment]
When you say it works on your machine, are you using the same test / gist script that's running in Travis?

At the moment the role runs inside of a Docker image for each distro, so in theory Travis' underlying OS is taken out of the equation. It's only responsible for curling down the script and running a Docker container for each tested distro.

**Comment by SuperSandro2000** [comment]
> When you say it works on your machine, are you using the same test / gist script that's running in Travis?

yes

> Travis' underlying OS is taken out of the equation
Not always cause docker is not a VM but I think that the 16.04 image is just to old.

**Comment by jpmat296** [comment]
Thanks for the fix. And to resolve the failed tests, I've changed 👍 

```
diff --git a/defaults/main.yml b/defaults/main.yml
index 29a6820..7698dc2 100644
--- a/defaults/main.yml
+++ b/defaults/main.yml
@@ -48,7 +48,7 @@ docker__apt_repository: >

 docker__pip_dependencies:
   - "gcc"
-  - "python-setuptools"
+  - "python{{ '3' if ansible_python.version.major == 3 else '' }}-setuptools"
   - "python{{ '3' if ansible_python.version.major == 3 else '' }}-dev"
   - "python{{ '3' if ansible_python.version.major == 3 else '' }}-pip"
   - "virtualenv"
```

Without this patch, python2 is installed even when python3 is used to run ansible.

HTH

**Comment by nickjj** [comment]
@jpmat296 so for clarity, your diff and all of super's changes to the role were required to get it to work with Ubuntu 16.04?

**Comment by SuperSandro2000** [comment]
I needed to change one thing in the test script to get systemd-reload working. So I just merged it into this repo. Also the environment change is required to get systemd-reload running. Then I reverted the removal of 16.04 and forced the venv to be python3. This is probably a bit cruel but docker-compose does not work with 2.7 anymore.

**Comment by nickjj** [comment]
I appreciate the efforts on this, but let's let Ubuntu 16.04 support rest in peace, see https://github.com/nickjj/ansible-docker/issues/95#issuecomment-765640359 for more details.

**Pull request closed without merging**
