### PR TITLE
add apt docker-{{ docker__edition }}-cli docker-{{ docker__edition }}-rootless-extras when updating

### PR DESCRIPTION
**Pull request by bobohb**
When upgrading the docker version also upgrade docker-{{ docker__edition }}-cli docker-{{ docker__edition }}-rootless-extras

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for the PR.

Can you describe a use case that happened where you ended up having a different CLI vs server version?

**Comment by bobohb** [comment]
Example: Install docker-ce 20.10.18 first, when you need to upgrade to 20.10.19, docker-ce will upgrade to 20.10.19, docker-ce-cli and docker-ce-rootless-extras will stay at 20.10.18

**Comment by bobohb** [comment]
Testing in Ubuntu 22.04.1

**Comment by nickjj** [comment]
How did you upgrade from 20.10.18 to 20.10.19?

**Comment by bobohb** [comment]
playbook

20.10.18

- name: Install docker
  hosts: all
  become: true

  roles:
    - role: "ansible-docker"
      vars:
        docker__version: "20.10.18"
        docker__state: "present"
        docker__compose_version: "1.29.2"
        docker__compose_v2_version: "2.11.2"
      tags: ["docker"]

20.10.19

- name: Install docker
  hosts: all
  become: true

  roles:
    - role: "ansible-docker"
      vars:
        docker__version: "20.10.19"
        docker__state: "latest"
        docker__compose_version: "1.29.2"
        docker__compose_v2_version: "2.11.2"
      tags: ["docker"]

**Comment by nickjj** [comment]
Thanks, that looks good.

Just letting you know it'll take me a few days to manually test this but I'm guessing it'll be good to go.

Can you force push an amended commit message of:

```
Explicitly install Docker CLI and rootless extras

Without doing this these packages won't get updated
when you install a new version of Docker.
```

**Comment by bobohb** [comment]
I have modified the commit message

**Comment by nickjj** [comment]
I'm able to reproduce this as well. After applying your patch it correctly updates the version for `docker --version`.

Before merging this, can you let me know what role the rootless extras package plays in this? Were there some tools that it installs which also need to be updated?

**Comment by bobohb** [comment]
Most of the time upgrading the docker version is to fix security issues
For security reasons, it is recommended to install the rootless extras package and run docker with a non-root user whenever appropriate
I checked the docker-ce dependencies and there should be no other packages that need to be explicitly specified

**Comment by nickjj** [comment]
I guess I'm having trouble seeing how the rootless extras falls inline with the versioning of Docker. Docker has the server (`docker-ce`) and client (`docker-cli`). Is rootless extras an optional plugin? Is its version dependent on which `docker-ce` version you install?

**Comment by nickjj** [comment]
Also the current Docker pin is for `docker-ce-*`, we'll need to add a new pin template for `docker-cli-*`.

**Pull request closed without merging**
