### PR TITLE
Add virtualenv_site_packages option

### PR DESCRIPTION
**Pull request by schrc3b6**
Adding virtualenv_site_packages option to not need to reinstall site packages in to the virtual environment.

### CODE REVIEW

**Comment by nickjj** [comment]
If you enable this, wouldn't this defeat the purpose of using virtual environments since it would use your global / system site-packages directory instead of installing an isolated version of the dependencies?

**Comment by schrc3b6** [comment]
Yes, it would use the system site packages if they are already installed, If not they will be installed in the virtual environment. 

Why I need this:
- I don't want to modify our system wide python installation
- I need to use non pypi python modules that are already system wide installed

I know I could split up playbooks and set python path in each playbook or use roles via include_role to set different python interpreter for each role. But inheriting site packages seem to be cleaner.

**Comment by nickjj** [comment]
> I need to use non pypi python modules that are already system wide installed

Which libraries?

**Comment by schrc3b6** [comment]
I have a legacy python script that gets everything in place before building a docker image. Instead of running the script via command module, I created a ansible module out of it. 

Because of legacy reason the script rechecks if all software is installed with the python-apt library.
But since this seems to be a way to specific case, I will try to get rid of the legacy code :)

Thanks

**Comment by schrc3b6** [comment]
Just noticed because of that, you also can't use the ansible apt module in a playbook with the python-docker interpreter set. 
However I can't come up with a good reason why you would need the apt module in a docker playbook.

**Comment by nickjj** [comment]
> can't use the ansible apt module in a playbook with the python-docker interpreter set.

Do you mean the pip module? Because I'm pretty sure the apt module wouldn't have any dependency or bearing on the Python interpreter. The docs don't mention that's something you can even configure.

**Comment by schrc3b6** [comment]
Imagine the following playbook:
```
# This is the playbook that sets up docker using your role
- import_playbook: docker-base.yml

- name: test
  hosts: "all"
  become: true

  vars:
    ansible_python_interpreter: "/usr/bin/env python-docker"

  # using the apt module for some crazy reason
  tasks:
  - name: install curl
    apt:
      name: curl

  - name: pull postgres
    docker_image:
      name: postgres:9-alpine
      source: pull
```
This will fail because the python apt module is not installed in the virtual environment.
`fatal: [m1]: FAILED! => {"changed": false, "msg": "Could not import python modules: apt, apt_pkg. Please install python3-apt package."}`
And apt was one of those python modules that can't be installed via pip if I remember correctly.

However I don't see that anybody would ever use the ansible apt module in a docker playbook.

**Comment by nickjj** [comment]
Ah, in that case I would attach the interpreter to the tasks that need it (such as the `docker_*` tasks like this role does) instead of globally for the whole playbook.

**Pull request closed without merging**
