### PR TITLE
ability to update apt's cache was added

### PR DESCRIPTION
**Pull request by gwaewion**

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for the PR, have you checked this comment btw https://github.com/nickjj/ansible-docker/pull/59#issuecomment-513504141?

**Comment by gwaewion** [comment]
@nickjj I've read it and I get the point. But I suggest only ability to update apt's cache. If anyone wants to do that he will be able, but by default nobody is going to touch that functionality.

**Comment by nickjj** [comment]
I'm on the fence for this one because if we do it here it's saying every role should have this behavior. It really feels like a responsibility outside of a role installing and configuring a specific package.

If you don't have a dedicated bootstrap role, what about running the update in `pre_tasks`?

**Comment by nickjj** [comment]
Going to close this one, sorry.

**Pull request closed without merging**
