### PR TITLE
Set become on relevant tasks

### PR DESCRIPTION
**Pull request by magick93**
Fix for https://github.com/nickjj/ansible-docker/issues/56

### CODE REVIEW

**Comment by nickjj** [comment]
Thanks for the contribution but I'm going to have to shoot down this PR.

If you set `become: true` at the playbook level then all of the tasks that need root access will have proper permissions. It's expected you run this role with `become: true`.

**Comment by magick93** [comment]
> Thanks for the contribution but I'm going to have to shoot down this PR.
> 
> If you set `become: true` at the playbook level then all of the tasks that need root access will have proper permissions. It's expected you run this role with `become: true`.

I maybe mistaken, but setting `become: true` at the playbook, or role, level doesnt mean that tasks that need root access work correctly but that all tasks run as root. 

The idea of using `become: true` at the task level is to apply it only where it is needed.

**Comment by magick93** [comment]
>  It's expected you run this role with become: true.

Yes, I'm already doing this, but it still resulted in a permissions error.

**Comment by nickjj** [comment]
When you set `become: true` at the playbook level, each task will run as the `become` user which is `root` by default (unless you specify something different).

> Yes, I'm already doing this, but it still resulted in a permissions error.

If you're getting a permission error, then `become: true` isn't being set. Maybe the indentation is messed up in your playbook. Paste your full playbook in the issue you opened before.

Going to close this PR since setting `become: true` for every task that needs root isn't necessary.

**Comment by magick93** [comment]
If it was an indentation issue the playbook wouldnt run.

And forcing users to set `become: true` at the playbook level means all roles, not just yours, will run as the specified user.

**Comment by nickjj** [comment]
If you have 1 playbook that uses many roles, you can set `become: true` at the `role` level to set it for a specific role.

Personally I just have a separate playbook tho that does nothing except run Docker.

In either case, you're not forced to set `become: true` for all roles in a playbook.

Also, check the issue you opened because I replied with a likely fix (your `become: true` wasn't being set).

**Comment by deimi** [comment]
@nickjj 

I also think that it would be better to use become only on those tasks which need it and not the whole role.
The problem now is that docker_login is executed as root as root and not as the ansible_user. This leads to the effect that the ~/.docker/config.json is generated with wrong permissions.

image

My ansible_user is "ubuntu" and is also added to the docker group. But every docker command leads to an error, because the user doesn't have permission to use the config.json

image

There is no need to execute the docker_login module as root, it only needs to be executed as a user whom belongs to the docker group.

**Comment by nickjj** [comment]
Pretty much every task needs root except for this one.

Did you add ubuntu user to the docker group and logout / login btw?

**Comment by deimi** [comment]
Yes, I did.  
It is clearly the fault of the permission for config.json. As you can see in the ```ll``` output, root is the owner of this file and root group is the only group which has read and write access to this file.

**Comment by nickjj** [comment]
If you change the permissions of the directory and file to `ubuntu:ubuntu` does it work?

I never ran into this issue btw.

**Comment by deimi** [comment]
Yes, if I manually change the permission after executing the ansible script, I can use docker as usual.

**Pull request closed without merging**
