### PR TITLE
[Fix] Lxc crash

### PR DESCRIPTION
**Pull request by jbsky**

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for the PR. What distro are you running in your LXC? This role only supports Python 3 btw.

**Comment by jbsky** [comment]
Hi,

Debian 10, Buster/stable.

**Comment by nickjj** [comment]
Does it have Python 3 installed and is it bootstrapped to run Ansible?

What is the exact error when you run the role?

I can't reproduce this error on a regular Debian 10 OS or within Docker using Debian 10 as a base.

**Comment by jbsky** [comment]
Does it have Python 3 installed and is it bootstrapped to run Ansible?
Interesting, i.e.?

What is the exact error when you run the role?
image

Anyway by passing everything in python 3, on the machine, when I connect, there is python 2.

**Comment by nickjj** [comment]
You can configure Ansible to use Python 3 by setting `ansible_python_interpreter`.

Python 2 has been officially end of life for 9 months now. It's highly recommended to use 3 everywhere.

**Comment by jbsky** [comment]
So

> 
> 
> You can configure Ansible to use Python 3 by setting `ansible_python_interpreter`.
> 
> Python 2 has been officially end of life for 9 months now. It's highly recommended to use 3 everywhere.

So, you have to evolve your readme by adding this as a prerequisite, make sure you are in python 3. Just add in the file ansible.cfg:
ansible_python_interpreter=/usr/bin/python3

**Comment by nickjj** [comment]
Thanks. Technically you might be able to get it going with Python 2 if you adjust the default variables to use the Python 2 version of the apt packages that get installed. It's just not supported officially.

**Pull request closed without merging**
