### PR TITLE
Set up config before installing

### PR DESCRIPTION
**Pull request by pcolmer**
This moves the creation of `daemon.json` to before Docker gets installed. This ensures that if `graph` is defined then Docker immediately uses it and initialises its workspace in the desired location.

Note that this change does not support `graph` being changed after Docker has been installed. More work is required for that :)

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks for the contribution.

But what made you decide to split up the tasks for both configuration directories?

**Comment by pcolmer** [comment]
> But what made you decide to split up the tasks for both configuration directories?

Lack of knowledge on my part, to be honest, combined with wanting to change as little as possible. 

I know what happens if I initialise `daemon.json` before Docker gets installed, but I don't know enough about what the other configuration bits are doing to be certain of the impact if I move those bits around.

**Comment by nickjj** [comment]
When in doubt, changing as little as possible is a good plan.

I'd be curious to see what would happen if you put both of them back together. I think there's a very high chance it will work with them together. One less task is always nice from both a maintainability and performance POV when it comes to Ansible.

**Comment by pcolmer** [comment]
I've tested this with the recombined config directory creation and it doesn't affect the installation of Docker.

**Comment by nickjj** [comment]
Thanks, can you also update the `CHANGELOG.md`, by changing it from this:

```md
## Next release

- **Backwards incompatible change:** `python-docker` was renamed to `python3-docker`
- Fix symlink related issues with virtualenv when using virtualenv 20+
- Remove all support for Python 2.x
- Officially remove support for Ubuntu 16.04
```

To this:

```md
## Next release

- **Backwards incompatible change:** `python-docker` was renamed to `python3-docker`
- Fix symlink related issues with virtualenv when using virtualenv 20+
- Configure daemon before installing Docker to allow customizing certain things
- Remove all support for Python 2.x
- Officially remove support for Ubuntu 16.04
```

You may need to pull the current master branch down locally to get the updated changelog since I updated it the other day.

Once that's done, we should be good to go.

**Comment by nickjj** [comment]
Done and merged. Thanks!

**Pull request merged**
