### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by alexinthesky**
package name changed starting with docker engine 12.4 :
 apt-cache madison docker-engine :

docker-engine | 1.13.0-0~debian-jessie | https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
docker-engine | 1.12.6-0~debian-jessie | https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
docker-engine | 1.12.5-0~debian-jessie | https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
docker-engine | 1.12.4-0~debian-jessie | https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
docker-engine | 1.12.3-0~jessie | https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
docker-engine | 1.12.2-0~jessie | https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

I think at this point it might make sense to use the latest Docker 17.03 release.

Also don't worry about the Travis test failing, it had always failed. Testing Docker within Docker is proving to be a challenge.

**Comment by alexinthesky** [comment]
all right, my modif still fits with the name they gave to the 17.03 package :+1: 
ust have to use docker_version: 17.03.0~ce

**Comment by nickjj** [comment]
Sorry, I'm not a fan of bringing in pip just to install Docker. There is an official Debian based package to install it already.

**Comment by alexinthesky** [comment]
ok no worries. I actually install pip & docker-py which in mandatory if you want to use the docker-container module from ansible

**Comment by nickjj** [comment]
Closing this as v17.06+ is now supported.

Thanks for the PR tho!

**Pull request closed without merging**
